[package]
name = "checkin"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14", features = ["tokio", "advanced"] }
chrono = "0.4"
anyhow = "1"
tokio = "1.52"
serde = { version = "1.0", features = ["derive"]}
uuid = { version = "1.23.4", features = ["serde"]}
toml = "0.9"
dirs = "6"

[package.metadata.scripts]
run = "cargo run"
build-debug = "cargo build"
build-release = "cargo build --release"
test = "cargo test -- --nocapture"
clean = "cargo clean"
