[package]
name = "checkin"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
anyhow = "1"
serde = { version = "1.0", features = ["derive"]}
uuid = { version = "1.23.4", features = ["serde"]}
toml = "0.9"
rand = "0.10.2"
dirs = "6"
tokio = "1.53"

# GUI
iced = { version = "0.14", features = ["tokio", "advanced", "svg", "advanced-shaping"] }

# Signture Recognization
bincode-next = "3.1.1"
nalgebra = "0.34"
dtw = "0.1"

[dev-dependencies]
image = "0.25"
serde_json = "1.0"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"